version: '3'

name: 'cqrs_project_example'

services:
  app_writer:
    container_name: app_writer
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    ports:
      - "5005:5005"
    networks:
      - cqrs
    
    depends_on:
      cqrs_kafka:
        condition: service_started
      cqrs_writer_db:
        condition: service_started

  cqrs_writer_db:
    container_name: cqrs_writer_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cqrs
    ports:
      - "5435:5432"
    volumes:
      - cqrs_volume:/var/lib/postgresql/data
    networks:
      - cqrs

  cqrs_zookeeper:
    container_name: cqrs_zookeeper
    image: bitnami/zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - cqrs
  
  cqrs_kafka:
    container_name: cqrs_kafka
    image: bitnami/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cqrs_zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - cqrs
    depends_on:
      cqrs_zookeeper:
        condition: service_started

  app_consumer:
    container_name: cqrs_consumer
    restart: always
    build:
      context: ./app_consumer
      dockerfile: docker/Dockerfile

    networks:
      - cqrs

  app_reader:
    container_name: cqrs_reader
    build:
      context: ./app_reader
      dockerfile: docker/Dockerfile
    
    ports:
      - "5006:5005"
    depends_on:
      cqrs_reader_db:
        condition: service_started

    networks:
      - cqrs
  
  cqrs_reader_db:
    container_name: cqrs_reader_db
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - cqrs_reader_volume:/data/db
    networks: 
      - cqrs


volumes:
  cqrs_volume:
    external: true
  cqrs_kafka_persist:
    external: true
  cqrs_reader_volume:
    external: true

networks:
  cqrs:
    external: true