# Use postgres/example user/password credentials
version: '3'

services:
  cqrs_db:
    container_name: cqrs_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cqrs
    ports:
      - "5435:5432"
    volumes:
      - cqrs_volume:/var/lib/postgresql/data
    networks:
      - cqrs
  
  cqrs_zookeeper:
    container_name: cqrs_zookeeper
    image: bitnami/zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - cqrs
  
  cqrs_kafka:
    container_name: cqrs_kafka
    image: bitnami/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cqrs_zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - cqrs
    depends_on:
      cqrs_zookeeper:
        condition: service_started

volumes:
  cqrs_volume:
    external: true
  cqrs_kafka_persist:
    external: true

networks:
  cqrs:
    external: true